services:
  # Backend Service (API)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house-api
    ports:
      - "8000:8000"
    volumes:
      # PERSISTENCE: Maps the local 'models' folder inside the container
      # Ensures saved data (pkl, registry.json) persists across restarts
      - ./models:/app/models
      # Optional: Maps source code for hot-reloading during development without rebuilding
      # - .:/app
      # RELIABILITY: Persists logs so you can analyze metrics after the container stops
      - ./app_metrics.log:/app/app_metrics.log

  # Frontend Service (Streamlit)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: house-frontend
    ports:
      - "8501:8501"
    environment:
      # The address must match the API service name defined above
      - API_URL=http://api:8000
    depends_on:
      - api

  # Performance & Reliability Metrics (Locust)
  locust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house-metrics-tester
    ports:
      - "8089:8089"
    volumes:
      - .:/app
    command: locust -f locustfile.py --host http://api:8000
    depends_on:
      - api